reksio:
  awake: false
  bornIn : Kolkata
  birthYear : 1987
  friends : 
    - Kulbeer
    - Abhilash
    - Anil
    - Saumil
    - Anish
    - Ritwik
  homepage : https://en.wikipedia.org/wiki/Reksio
  grades : 
    Math : A
    PE : A
    Bengali : A
