reksio:
  awake: true
  bornIn : Kolkata
  birthYear : 1987
  friends : 
   - Kulbeer
   - Anil
   - Tapas
   - Shalmoli
  homepage : https://en.wikipedia.org/wiki/Arka_Dutta/
  points: 
    Math : 92
    PE : 99
    Bengali : 90
